import { Card, CardContent } from "@/components/ui/card"

interface Props {
  narrative: string
  scoreConfidence: number
}

export function NarrativeSection({ narrative, scoreConfidence }: Props) {
  return (
    <section
      data-testid="narrative-section"
      aria-label="Narrative summary"
      className="px-4 md:px-8"
    >
      <Card className="py-5">
        <CardContent className="px-5 space-y-3">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
            Narrative
          </h2>
          <p className="text-base leading-relaxed">{narrative}</p>
          <p className="text-xs text-muted-foreground">
            Generated by Gemini 2.5 Flash. Specific dollar amounts are approximate.
            Score confidence: {Math.round(scoreConfidence * 100)}% of weights backed by real data.
          </p>
        </CardContent>
      </Card>
    </section>
  )
}
